M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Thu 25 May 2023 01:32:15 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-25T13:32:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0571
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X7.1669Y-3.4204
T2
X7.8418Y-2.6555
X7.8418Y-3.3838
T3
X7.1669Y-2.6331
T0
M30
